### ISSUE TITLE
Support notes on accounts

### ISSUE THREAD

**Issue by jantman** [konomae/lastpass-python#22]
While they're present in the API response, it seems like the "Notes" field of accounts is silently discarded. It would be nice if that was preserved.

Similarly, I don't understand why only certain types of notes are supported... the API responses clearly include even "Generic" free-form notes entries, but they're silently discarded...

**Comment by jantman** [comment]
I've opened #26 to fix this

**Comment by konomae** [comment]
Thank you for reporting this!
#26 is merged.
