### ISSUE TITLE
Secure notes not included

### ISSUE THREAD

**Issue by mattiash** [konomae/lastpass-python#28]
I have been running an old version of lastpass-python (76d6e98769d5bcb8288e1c6767030b934f5cf748 from May 2014) for a long time without any problems to access both "Sites" and "Secure notes" in my lastpass account (via vault.accounts). Today, I decided that I wanted to access the Notes-field for accounts, so I upgraded to lastpass-python master. I can now see the Notes-field, but ufortunately I can't seem to access the Secure notes any more. I can't seem to find them anywhere when looping through all accounts.

Is it possible to access the Secure notes somehow with a recent lastpass-python?

**Comment by konomae** [comment]
@mattiash Thank you for reporting this!

Created new branch: https://github.com/konomae/lastpass-python/tree/feature/return-all-accounts
Could you retry with this?

**Comment by mattiash** [comment]
That branch works perfectly. Thank you!

**Comment by konomae** [comment]
v0.3.0 released!
