### ISSUE TITLE
420 response code from /login.php

### ISSUE THREAD

**Issue by steinkel** [konomae/lastpass-python#46]
We're getting a 420 response error (empty response content) from /login.php endpoint

We're able to login using the lastpass web interface correctly. Are you getting similar issues on login?

```
('Unexpected error:', <class 'lastpass.exceptions.NetworkError'>)

**Comment by erlichsefi** [comment]
@steinkel I'm having the same issue too, did you solved it?

**Comment by erlichsefi** [comment]
Hi @steinkel, solve this by updating to the lastpass-python last version and by following the solution suggested here https://github.com/lastpass/lastpass-cli/issues/604

**Comment by steinkel** [comment]
Thank you @erlichsefi the update fixed our issue
